In [ ]:
import json
import pennylane as qml
import pennylane.numpy as np

n_qubits = 9
dev = qml.device("default.qubit", wires=n_qubits)
error_dict = {0: 'PauliX', 1: 'PauliY', 2: 'PauliZ'}

def error(error_key, qubit):
    """Defines the error that is induced in the circuit.

    Args:
        error_key (int): An integer associated to the type of error (Pauli X, Y, or Z)
        qubit (int): The qubit that the error occurs on.
    """
    getattr(qml, error_dict[error_key])(qubit)

@qml.qnode(dev)
def shor(state, error_key, qubit):
    """A circuit defining Shor's code for error correction.

    Args:
        state (list(float)): The quantum state of the first qubit in the circuit.
        error_key (int): An integer associated to the type of error (Pauli X, Y, or Z)
        qubit (int): The qubit that the error occurs on.

    Returns:
        (list(float)): The expectation value of the Pauli Z operator on every qubit.
    """
    qml.QubitStateVector(np.array(state), wires=0)


    # Put your code here #
    qml.CNOT(wires = [0,3])
    qml.CNOT(wires = [0,6])
    for i in range(3):
        qml.Hadamard(wires = 3*i)
        qml.CNOT(wires = [3*i,3*i+1])
        qml.CNOT(wires = [3*i,3*i+2])
    error(error_key,qubit)
    for i in range(3):
        qml.CNOT(wires = [3*i,3*i+1])
        qml.CNOT(wires = [3*i,3*i+2])
        qml.Toffoli(wires = [3*i+2,3*i+1,3*i])
        qml.Hadamard(wires = 3*i)
    qml.CNOT(wires = [0,3])
    qml.CNOT(wires = [0,6])
    qml.Toffoli(wires = [6,3,0])

    return [qml.expval(qml.PauliZ(i)) for i in range(n_qubits)]
        


# These functions are responsible for testing the solution.
def run(test_case_input: str) -> str:
    state, error_key, qubit = json.loads(test_case_input)
    output = shor(state, error_key, qubit).tolist()

    return str(output)

def check(solution_output: str, expected_output: str) -> None:
    solution_output = json.loads(solution_output)
    expected_output = json.loads(expected_output)

    assert np.allclose(solution_output, expected_output, rtol=1e-4)


test_cases = [['[[0, 1], 0, 3]', '[-1.0,  1.0,  1.0,  1.0, -1.0, -1.0,  1.0,  1.0,  1.0]']]

for i, (input_, expected_output) in enumerate(test_cases):
    print(f"Running test case {i} with input '{input_}'...")

    try:
        output = run(input_)

    except Exception as exc:
        print(f"Runtime Error. {exc}")

    else:
        if message := check(output, expected_output):
            print(f"Wrong Answer. Have: '{output}'. Want: '{expected_output}'.")

        else:
            print("Correct!")

0

In [10]:
import sympy as sp

In [45]:
a = list(sp.symbols('a0:32'))

In [86]:
state = sp.zeros(32,1)
nums = [14,15,22,23,26,27,28,29]
for num in nums:
    state[num] = a[num]

In [95]:
state

Matrix([
[  0],
[  0],
[  0],
[  0],
[  0],
[  0],
[  0],
[  0],
[  0],
[  0],
[  0],
[  0],
[  0],
[  0],
[a14],
[a15],
[  0],
[  0],
[  0],
[  0],
[  0],
[  0],
[a22],
[a23],
[  0],
[  0],
[a26],
[a27],
[a28],
[a29],
[  0],
[  0]])

In [88]:
m1*state

Matrix([
[      0],
[      0],
[      0],
[      0],
[      0],
[      0],
[      0],
[      0],
[      0],
[      0],
[      0],
[      0],
[      0],
[      0],
[1.0*a14],
[1.0*a15],
[      0],
[      0],
[      0],
[      0],
[      0],
[      0],
[1.0*a22],
[1.0*a23],
[      0],
[      0],
[1.0*a26],
[1.0*a27],
[1.0*a29],
[1.0*a28],
[      0],
[      0]])

In [89]:
np.matrix(m2@state)

matrix([[0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1.0*a14],
        [1.0*a15],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1.0*a22],
        [1.0*a23],
        [0],
        [0],
        [1.0*a27],
        [1.0*a26],
        [1.0*a28],
        [1.0*a29],
        [0],
        [0]], dtype=object)

In [90]:
np.matrix(m3@state)

matrix([[0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1.0*a14],
        [1.0*a15],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1.0*a23],
        [1.0*a22],
        [0],
        [0],
        [1.0*a26],
        [1.0*a27],
        [1.0*a28],
        [1.0*a29],
        [0],
        [0]], dtype=object)

In [91]:
np.matrix(m4@state)

matrix([[0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1.0*a15],
        [1.0*a14],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1.0*a22],
        [1.0*a23],
        [0],
        [0],
        [1.0*a26],
        [1.0*a27],
        [1.0*a28],
        [1.0*a29],
        [0],
        [0]], dtype=object)

In [102]:
for num in nums:
    print(bin(num)[2:].zfill(5))

01110
01111
10110
10111
11010
11011
11100
11101


In [ ]:
01110, 10110, 11010, 11100 -> entangle them: (0111 + 1011 + 1101 + 1110)0

In [ ]:
01111, 10111, 11011, 11101 -> entangle them: (0111 + 1011 + 1101 + 1110)1

In [ ]:
(1110 + 1101 + 1011)0 + (0111)1

In [ ]:
(1110 + 1101 + 1011)0 -(0111)1
(1110 + 1101 + 1011)1 -(0111)0

In [ ]:
(0111 + 1011 + 1101 + 1110)(0-1)
(1110 + 1101 + 1011)(0-1) + (0111)(1-0)

In [244]:
import json
import pennylane as qml
import pennylane.numpy as np

dev = qml.device("default.qubit", wires=[0,1,2,3,4], shots=1)
dev.operations.add("op")

wires = [0,1,2,3,4]


@qml.qnode(dev)
def circuit(project_execution):
    """This is the circuit we will use to detect which is the lazy worker. Remember 
    that we will only execute one shot.

    Args:
        project_execution (qml.ops): 
            The gate in charge of marking in the last qubit if the project has been finished
            as indicated in the statement.

    Returns:
        (numpy.tensor): Measurement output in the 5 qubits after a shot.
    """
    
    # Put your code here #
    qml.PauliX(wires = wires[4])
    for i in range(5):
        qml.Hadamard(wires[i])
    project_execution
    for i in range(5):
        qml.Hadamard(wires[i])
    return [qml.vn_entropy(wires = [i]) for i in wires]
    
def process_output(measurement):
    """This function will take the circuit measurement and process it to determine who is the lazy worker.

    Args:
        measurement (numpy.tensor): Measurement output in the 5 qubits after a shot.

    Returns:
        (str): This function must return "e1", "e2" "e3" or "e4" - the lazy worker.
    """
    # Put your code here #
    print(measurement)
    if np.isclose(measurement[1][3],0):
        return 'e4'
    elif np.isclose(measurement[1][5],0):
        return 'e3'
    elif np.isclose(measurement[1][9],0):
        return 'e2'
    else:
        return 'e1'
    


# These functions are responsible for testing the solution.

def run(test_case_input: str) -> str:
    return None

def check(solution_output: str, expected_output: str) -> None:
    samples = 5

    solutions = []
    output = []

    for s in range(samples):
        lazy = np.random.randint(0, 4)
        lazy=1
        no_lazy = list(range(4))
        no_lazy.pop(lazy)

        def project_execution(wires):
            class op(qml.operation.Operator):
                num_wires = 5

                def compute_decomposition(self, wires):
                    raise ValueError("You cant descompose this gate")

                def matrix(self):
                    m = np.zeros([32, 32])
                    for i in range(32):
                        b = [int(j) for j in bin(64 + i)[-5:]]
                        if sum(np.array(b)[no_lazy]) == 3:
                            if b[-1] == 0:
                                m[i, i + 1] = 1
                            else:
                                m[i, i - 1] = 1
                        else:
                            m[i, i] = 1
                    print(m)
                    return m

            op(wires=wires)
            return None
        
        
        #out = circuit(wires_c)
        out = circuit(project_execution)
        solutions.append(lazy + 1)
        output.append(int(process_output(out)[-1]))
        print(process_output(out),lazy+1)
        

    assert np.allclose(
        output, solutions, rtol=1e-4
    ), "Your circuit does not give the correct output."

    ops = [op.name for op in circuit.tape.operations]
    #assert ops.count("op") == 1, "You have used the oracle more than one time."


test_cases = [['No input', 'No output']]

for i, (input_, expected_output) in enumerate(test_cases):
    print(f"Running test case {i} with input '{input_}'...")

    try:
        output = run(input_)

    except Exception as exc:
        print(f"Runtime Error. {exc}")

    else:
        if message := check(output, expected_output):
            print(f"Wrong Answer. Have: '{output}'. Want: '{expected_output}'.")

        else:
            print("Correct!")

Running test case 0 with input 'No input'...
[1.55431223e-15 1.55431223e-15 1.55431223e-15 1.55431223e-15
 1.55431223e-15]


IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [237]:
import json
import pennylane as qml
import pennylane.numpy as np

dev = qml.device("default.qubit", wires=[0,1,2,3,4], shots=1)
dev.operations.add("op")

wires = [0,1,2,3,4]


@qml.qnode(dev)
def circuit():
    """This is the circuit we will use to detect which is the lazy worker. Remember 
    that we will only execute one shot.

    Args:
        project_execution (qml.ops): 
            The gate in charge of marking in the last qubit if the project has been finished
            as indicated in the statement.

    Returns:
        (numpy.tensor): Measurement output in the 5 qubits after a shot.
    """
    
    # Put your code here #
    qml.PauliX(wires = wires[4])
    for i in range(5):
        qml.Hadamard(wires[i])
    qml.MultiControlledX(wires = [0,1,2,4])
    for i in range(5):
        qml.Hadamard(wires[i])
    return [qml.vn_entropy(wires = [i]) for i in wires]
circuit()

tensor([5.62335145e-01, 5.62335145e-01, 5.62335145e-01, 1.55431223e-15,
        1.55431223e-15], requires_grad=True)